

star_bits = {'gel', 'si', 'meg', 'jab', 'kor', 'ber', 'lux', 'ja', 'xa', 'pin', 'qu', 'ens', 'wat',
'kaf', 'glo', 'eia', 'wiy', 'ci', 'lí', 'gin', 'muph', 'phe', 'sche', 'cock', 'sic', 'bih', 'bi',
'iib', 'skat', 'alu', 'bh', 'eby', 'rin', 'ruch', 'can', 'soň', 'cer', 'em', 'nath', 'tes', 'gar',
'con', 'asp', 'ok', 'bu', 'caph', 'min', 'nacht', 'da', 'ham', 'nus', 'pi', 'pea', 'pua', 'stri',
'tang', 'man', 'zaa', 'dach', 'win', 'nab', 'hor', 'ang', 'no', 'ti', 'ta', 'trix', 'va', 'ner',
'pú', 'mer', 'lum', 'za', 'dhi', 'un', 'nasl', 'ma', 'diph', 'cen', 'sal', 'franz', 'veh', 'jis',
'yil', 'gru', 'al', 'bar', 'rud', 'jam', 'kaa', 'ar', 'it', 'rux', 'um', 'ird', 'scha', 'ras', 'mönch',
'phec', 'ab', 'nal', 'faf', 'ris', 'lís', 'kham', 'nia', 'a', 'kal', 'ark', 'zirr', 'eb', 'cor', 'cit',
'ash', 'lil', 'rus', 'op', 'uh', 'per', 'tâ', 'pri', 'sym', 'lix', 'lun', 'lim', 'ni', 
'má', 'du', 'zhang', 'cu', 'bia', 'gi', 'mon', 'spi', 'rami', 'pol', 'fat', 'e', 'mal', 'phard', 
'nah', 'pet', 'pher', 'wazn', 'in', 'nen', 'fu', 'oltr', 'mat', 'ia', 'na', 'xi', 'uu', 'hil', 'sol', 'cas', 'nit',
'il', 'á', 'dah', 'ga', 'ai', 'ge', 'shat', 'has', 'bot', 'les', 'to', 'rid',
'lotl', 'kar', 'sec', 'én', 'ren', 'ill', 'me', 'suud', 'nel', 'ik', 'ri', 'fe', 'que', 'ki', 'ops', 'axó',
'sho', 'le', 'bay', 'ser', 'ich', 'so', 'thu', 'lit', 'pha', 'im', 'fik', 'bup', 'she', 'din', 'mpin', 'pro',
'nar', 'be', 'ter', 'mol', 'do', 'sar', 'star', 'kad', 'nin', 'vin', 'ir', 'zar', 'salm', 'scept', 'kib', 'ib',
'tra', 'on', 'maa', 'is', 'dzi', 'pho', 'hi', 'hae', 'lyr', 'fera', 'ple', 'crus', 'kap', 'firk', 'sath', 'zos',
'pus', 'ath', 'sā', 'dom', 'ros', 'gak', 'sadr', 'sha', 'asc', 'ek', 'dub', 'nev', 'ha', 'mi', 'fal', 'fa', 'der',
'ca', 'pe', 'mot', 'xu', 'gen', 'bun', 'ba', 'ze', 'und', 'tar', 'bal', 'nard', 'graf', 'men', 'fo', 'ehy', 'nahn',
'lus', 'hog', 'lik', 'gol', 'iw', 'nil', 'nun', 'jid', 'mam', 'ka', 'gac', 'niy', 'ed', 'bur', 'lah', 
'dum', 'vel', 'ey', 'cy', 'lin', 'am', 'mir', ' star', 'mus', 'dha', 'fi', 'iph', 'the', 'pip', 'po', 'tral', 'gas',
'at', 'auk', 'og', 'ceb', 'muy', 'ru', 'yu', 'shar', 'lis', 'dal', 'hui', 'ac', 'mok', 'tal', 'tro', 'tha', 'tle',
'cher', 'su', 'wag', 'get', 'kes', 'es', 'we', 'gu', 'chir', 'ut', 'gor', 'i', 'pherg', 'er', 'dar', "'s", 'az', 'te',
'nir', 'kang', 'ec', 'keb', 'bik', 'bit', 'cyon', 'u', 'sac', 'yi', 'kraz', 'wady', 'os', 'wa', 'hu', 'la', 'de', 'kur', 'chi', 'ro', 
'dun', 'cha', 'oc', 'bol', 'ster', 'lay', 'lar', 'res', 'pa', 'hel', 'nek', 'aus', 'ruk', 'sam', 
'an', 'ler', 'vi', 'dus', 'bra', 'as', 'pai', 'di', 'wan', 'ur', 'neb', 'san', 'hak', 'li', 'fang', 'nu', 'hya',
'mu', 'he', 'rak', 'nya', 'ud', 'ty', 'hal', 'jah', 'nor', 'nás', 'sa', 'ku', 'zen', 'reo', 'lii', 'el', 'tis', 'cun',
'pã', 'rock', 'fin', 'ken', 'gil', 'oth', 'tu', 'prae', 'rix', 'meb', 'ko', 'dschub', 'nic', 'ay', 'teg', 'for', 'leph',
'ap', 'av', 'if', 'nan', 'rai', 'ra', 'co', 'gun', 'ul', 'ad', 'rab', 'bo', 'zu', 'zi', 'cur', 'hā', 'nep', 'deb', 'kah',
'leh', 'phact', 'us', 'zam', 'dì', 'gud', 'ach', 'mek', 'bel', 'pos', 'wur', 'tarf', 'uk', 'hma', 'o', 'ram', 'huc', 'go',
'thim', 'hah', 'dul', 'arc', 'kab', 'hra', 'rez', 'ratz', 'or', 'en', 'che', 'fle', 've', 'bél', 'ak', 'sim', 'ho', 'rum',
'et', 'yed', 'mo', 'del', 'se', 'ton', 'rach', 'shi', 'cel', 'hen', 'mach', 'sham', 'lich', 'lai', 'wö', 'sep', 'bat', 'gue',
'jat', 'kuy', 'pel', 'syr', 'nem', 'sci', 'bet', 'net', 'iy', 'ban', 'chab', 'ub', 'bah', 'mar', 'leo', 'tor', 'zed', 'iz', 'hai',
'ce', 'las', 'sat', 'ke', 'ne', 'ah', 'kent', 'tan', 'sub', 'bib', 'van', 'hrah', 'tas', 
're', 'fak', 'por', 'tay', 'mah', 'far', 'id', 'au', 'yid', 'lu', 'ran', 'kan', 'jil', 'ya', 'bor', 'bus'}


